name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: feature/250422

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    - run: mdbook build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
